import { test, expect, type Page } from "@playwright/test";
const card = (page: Page) => page.getByRole("region", { name: "Alex Example participation", exact: true });
const trigger = (page: Page, direction: string) => card(page).getByRole("button", { name: `Edit ${direction} for Alex Example`, exact: true });
const editor = (page: Page, direction: string) => card(page).getByRole("region", { name: `Alex Example ${direction} editor`, exact: true });
test.beforeEach(async ({ page, request }) => {
  await request.post("http://127.0.0.1:54329/test/reset");
  await page.goto("/sign-in");
  await page.getByLabel("Email address").fill("adult@example.com");
  await page.getByRole("button", { name: "Send code", exact: true }).click();
  await page.getByLabel("Sign-in code").fill("123456");
  await page.getByRole("button", { name: "Verify code" }).click();
  await expect(page).toHaveURL(/\/account$/);
  const result = await request.post("http://127.0.0.1:54329/test/matching");
  await page.goto((await result.json()).url);
});
test("compact cards preserve independent drafts and restore focus on save and cancel", async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 800 });
  await expect(page.getByLabel("Household participation summary")).toHaveText("2 participants · 2 going · 0 ride preferences incomplete");
  await expect(card(page).getByRole("combobox")).toHaveCount(0);
  const attendance = card(page).getByRole("button", { name: /^Edit attendance/ });
  await attendance.click();
  await expect(card(page).getByRole("combobox", { name: "Attendance", exact: true })).toBeFocused();
  await card(page).getByRole("combobox", { name: "Attendance", exact: true }).selectOption("not_going");
  await expect(page.getByLabel("Household participation summary")).toContainText("2 going");
  await card(page).getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(attendance).toBeFocused();
  await attendance.click();
  await expect(card(page).getByRole("combobox", { name: "Attendance", exact: true })).toHaveValue("going");
  await card(page).getByRole("button", { name: "Cancel", exact: true }).click();
  await trigger(page, "to event").click();
  const to = editor(page, "to event"), from = editor(page, "from event");
  await to.getByRole("combobox", { name: "Ride mode", exact: true }).selectOption("need_ride");
  await to.getByLabel("Earliest (America/New_York)", { exact: true }).fill("2098-12-31T03:30");
  await trigger(page, "from event").click();
  await expect(from.getByRole("combobox", { name: "Ride mode", exact: true })).toBeFocused();
  await from.getByRole("combobox", { name: "Ride mode", exact: true }).selectOption("self_transport");
  await from.getByRole("button", { name: "Save ride preference" }).click();
  await expect(card(page).getByRole("status")).toHaveText("Saved.");
  await expect(from).toHaveCount(0);
  await expect(trigger(page, "from event")).toBeFocused();
  await expect(to.getByRole("combobox", { name: "Ride mode", exact: true })).toHaveValue("need_ride");
  await expect(to.getByLabel("Earliest (America/New_York)", { exact: true })).toHaveValue("2098-12-31T03:30");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await to.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(trigger(page, "to event")).toBeFocused();
  await trigger(page, "to event").click();
  await expect(to.getByRole("combobox", { name: "Ride mode", exact: true })).toHaveValue("either");
  const order = await page.locator('[aria-label="Alex Example participation"], [aria-label="Confirmed carpool rides"], [aria-label="To event matches"]').evaluateAll(nodes => nodes.map(node => node.getAttribute("aria-label")));
  expect(order).toEqual(["Alex Example participation", "Confirmed carpool rides", "To event matches"]);
  await attendance.click();
  await card(page).getByRole("combobox", { name: "Attendance", exact: true }).selectOption("not_going");
  await card(page).getByRole("button", { name: "Save attendance" }).click();
  await expect(card(page).getByText("Not attending this occurrence.", { exact: true })).toBeVisible();
  await expect(to).toHaveCount(0);
  await expect(page.getByLabel("Household participation summary")).toContainText("1 going");
});
test("failed saves keep drafts open and pending disables only that editor", async ({ page }) => {
  await trigger(page, "to event").click();
  await trigger(page, "from event").click();
  const to = editor(page, "to event"), from = editor(page, "from event");
  await to.getByRole("combobox", { name: "Ride mode", exact: true }).selectOption("none");
  let release: (() => void) | undefined;
  const gate = new Promise<void>(resolve => { release = resolve; });
  await page.route("**/*", async route => {
    if (route.request().headers()["next-action"] && route.request().postData()?.includes('"ride"')) {
      await gate; await route.abort();
    } else await route.continue();
  });
  await to.getByRole("button", { name: "Save ride preference" }).click();
  await expect(to.getByRole("button", { name: "Cancel", exact: true })).toBeDisabled();
  await expect(from.getByRole("button", { name: "Cancel", exact: true })).toBeEnabled();
  release?.();
  await expect(to.getByRole("status")).toHaveText("Unable to connect. Please try again.");
  await expect(to.getByRole("combobox", { name: "Ride mode", exact: true })).toHaveValue("none");
  await expect(to.getByRole("button", { name: "Cancel", exact: true })).toBeEnabled();
});
test("household switching clears drafts and query parameters cannot override the header", async ({ page }) => {
  await trigger(page, "to event").click();
  await editor(page, "to event").getByRole("combobox", { name: "Ride mode", exact: true }).selectOption("none");
  const household = page.getByRole("combobox", { name: "Current household", exact: true });
  await household.selectOption({ label: "Other own household" });
  await expect(page.getByText("Household: Other own household", { exact: true })).toBeVisible();
  await expect(card(page)).toHaveCount(0);
  await page.goto("/groups/match-club/match-event?household=33333333-3333-4333-8333-333333333333");
  await expect(page.getByText("Household: Other own household", { exact: true })).toBeVisible();
  await household.selectOption({ label: "Example household" });
  await expect(card(page)).toBeVisible();
  await expect(card(page).getByRole("combobox")).toHaveCount(0);
  await trigger(page, "to event").click();
  await expect(editor(page, "to event").getByRole("combobox", { name: "Ride mode", exact: true })).toHaveValue("either");
});
